const options: Options = {
  prefix: 'console',
  colors: true,
  header: true,
  lines: true,
  linesChar: '·',
  dateLocale: 'en',
  username: true,
  datetime: true,
  platform: true,
  mainModule: true,
  disabled: false,
  seamless: false,
  showLogHash: false,
  alwaysSave: false,
  alwaysQuiet: false,
  logDir: '',
  format: {},
  callCount: false,
  linebreak: false,
  headerTextColor: 'gray',
  slackWebHookUrl: null,
  slackDisabled: false,
  onLog: () => {},
};

export default options; 